application: midas20160226
version: 1
runtime: python27
api_version: 1
threadsafe: true

#Start Handlers
handlers:

- url: /AK/*
  static_dir: /*

- url: /AL/*
  static_dir: /*

- url: /AR/*
  static_dir: /*

- url: /AZ/*
  static_dir: /*

- url: /CA/*
  static_dir: /*

- url: /CO/*
  static_dir: /*

- url: /CT/*
  static_dir: /*

- url: /DC/*
  static_dir: /*

- url: /DE/*
  static_dir: /*

- url: /FL/*
  static_dir: /*

- url: /GA/*
  static_dir: /*

- url: /HI/*
  static_dir: /*

- url: /IA/*
  static_dir: /*

- url: /ID/*
  static_dir: /*

- url: /IL/*
  static_dir: /*
- url: /IN/*
  static_dir: /*

- url: /KS/*
  static_dir: /*

- url: /KY/*
  static_dir: /*

- url: /LA/*
  static_dir: /*


- url: /MA/*
  static_dir: /*

- url: /MD/*
  static_dir: /*

- url: /ME/*
  static_dir: /*

- url: /MI/*
  static_dir: /*

- url: /MN/*
  static_dir: /*

- url: /MO/*
  static_dir: /*

- url: /MS/*
  static_dir: /*

- url: /MT/*
  static_dir: /*
- url: /NC/*
  static_dir: /*

- url: /ND/*
  static_dir: /*

- url: /NE/*
  static_dir: /*

- url: /NH/*
  static_dir: /*

- url: /NJ/*
  static_dir: /*

- url: /NM/*
  static_dir: /*

- url: /NV/*
  static_dir: /*

- url: /NY/*
  static_dir: /*

- url: /OH/*
  static_dir: /*

- url: /OK/*
  static_dir: /*

- url: /OR/*
  static_dir: /*

- url: /PA/*
  static_dir: /*

- url: /RI/*
  static_dir: /*

- url: /SC/*
  static_dir: /*

- url: /SD/*
  static_dir: /*

- url: /TN/*
  static_dir: /*

- url: /TX/*
  static_dir: /*

- url: /UT/*
  static_dir: /*

- url: /VA/*
  static_dir: /*

- url: /VT/*
  static_dir: /*

- url: /WA/*
  static_dir: /*

- url: /WI/*
  static_dir: /*

- url: /WV/*
  static_dir: /*

- url: /WY/*
  static_dir: /*

- url: /frontEnd
  static_dir: frontEnd

- url: .*
  script: csvparse.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
